# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PineBoat
author: Vijayabharathi
description: > # this means to ignore newlines until "baseurl:"
  Web development is weird. It is easy to learn, difficult to do it right, much easier to forget. If you are not enthusiastic about learning new things every day, you will also have the luxury of travelling back in time by the sheer progress being made on all ends.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pineboat.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vijayabharathib
github_username:  vijayabharathib
google_analytics: UA-80881928-2
permalink: /:title/
# Build settings
markdown: kramdown
#theme: jekyll-theme-midnight
gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
