baseURL: "https://www.pineboat.in/"
languageCode: "en-us"
title: "PineBoat"
theme: "beehive"
canonifyURLs: true
paginate: 10
# GDPR is good ! googleAnalytics: "UA-80881928-2"
publishDir: "public"
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: false
menu:
  main:
      - Name: "Home"
        Identifier: "home"
        URL: "/"
        weight: 101
      - Name: "About"
        Identifier: "about"
        URL: "/page/about/"
        weight: 220
      - Name: "Search"
        Identifier: "search"
        URL: "/page/search"
        weight: 333
      # - Name: "Privacy"
      #   Identifier: "privacy"
      #   URL: "/page/privacy_policy/"
      #   weight: 110
params:
  subtitle: "On shipping web"
  analytics: "https://unar.herokuapp.com/visits"
  algolia: 
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]

author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"

related:
  threshold: 80
  includeNewer: true
  indices:
    - name: categories 
      weight: 200
    - name: tags
      weight: 100
    - name: date
      weight: 10

outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home: 
    - HTML
    - RSS 
    - Algolia
    