baseURL: "https://pineboat.in/"
languageCode: "en-us"
title: "PineBoat"
theme: "beehive"
canonifyURLs: true
paginate: 10
googleAnalytics: "UA-80881928-2"
publishDir: "public"
author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"
