baseURL: "https://www.pineboat.in/"
languageCode: "en-us"
title: "PineBoat"
theme: "beehive"
canonifyURLs: true
paginate: 10
# GDPR is good ! googleAnalytics: "UA-80881928-2"
publishDir: "public"
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: true
menu:
  main:
      - Name: "About"
        Identifier: "about"
        URL: "/page/about/"
        weight: 220
      - Name: "Privacy"
        Identifier: "privacy"
        URL: "/page/privacy_policy/"
        weight: 110
params:
  subtitle: "On shipping web"
author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"
