---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/draft
  label: Draft
  create: all
  match: "**/*"
- type: directory
  path: content/edit
  label: Edit
  create: all
  match: "**/*"
- type: directory
  path: content/page
  label: Page
  create: all
  match: "**/*"
- type: directory
  path: content/author
  label: Author
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.47'
